# Services
apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
  labels:
    app: ngnix-app
spec:
  selector:
    app: ngnix-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80	