apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-emptydir
    volumeMounts:
    - name: cache-volume
      mountPath: /empty-dir
  volumes:
  - name: cache-volume
    emptyDir: {}