apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
      - name: nginx-volume
        mountPath: /etc/cfg
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
   - name: nginx-volume
     configMap:
       name: cfgvolume
 #     items:
 #     - key: var1
 #       path: var_path/subpath