apiVersion: v1
kind: Servicemetadata:  creationTimestamp: null  labels:    run: wordpress
  name: wordpressspec:  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31004
  selector:
    run: wordpress
  type: NodePort
status:
  loadBalancer: {}