apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306

  selector:
    run: wordpress
    run: mysql
  type: NodePort
status:
  loadBalancer: {}