apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-2
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['sleep','5000']
    ##alternate way to give the command
    #command
      #- "sleep"
      #- "5000"
