apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
spec:
  containers:
  - name: webapppod
    image: kodekloud/webapp-color
    args: ['--color','green']
    envFrom:
      - configMapRef:
          name: webapp-config-map
      - secretRef:
          name: db-scret
    env:
      - name: APP_COLOR # define the config variable directly
        value: red
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef: # map the config variable from config map
            name: webapp-config-map
            key: APP_COLOR