apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2020-02-05T18:11:45Z
  name: webapp
  namespace: default
  resourceVersion: "4117"
  selfLink: /api/v1/namespaces/default/pods/webapp
  uid: f84c9667-4842-11ea-932b-0242ac110006
spec:
  containers:
  - env:
    - name: LOG_HANDLERS
      value: file
    image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: event-simulator
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pxdlt
      readOnly: true
    - mountPath:  /log
      name: myvol
  dnsPolicy: ClusterFirst
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-pxdlt
    secret:
      defaultMode: 420
      secretName: default-token-pxdlt
  - name: myvol
    persistentVolumeClaim:
      claimName: claim-log-1
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2020-02-05T18:11:45Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2020-02-05T18:11:53Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2020-02-05T18:11:45Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://08d4697c7e26de03f336611b1294d52556740cae569bfa2b4da51358470aab05
    image: kodekloud/event-simulator:latest
    imageID: docker-pullable://kodekloud/event-simulator@sha256:1e3e9c72136bbc76c96dd98f29c04f298c3ae241c7d44e2bf70bcc209b030bf9
    lastState: {}
    name: event-simulator
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2020-02-05T18:11:53Z
  hostIP: 172.17.0.9
  phase: Running
  podIP: 10.40.0.1
  qosClass: BestEffort
  startTime: 2020-02-05T18:11:45Z