apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend # should match with pod label
  template: # Details about pod
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx