apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
data:
  DB-User: cm9vdA== # Incase of yaml file, literal values need to set as base 64 encode. IN imprative cmds it is not required
  DB_Host: c3FsMDE=
stringData:
  username: administrator