apiVersion: v1
kind: Pod
metadata:
  name: Pod with volume
spec:
  containers:
    - name: container with volume
      image: imagename
      command: [""]
      args: [""]
      volumeMounts:
        - mountPath: /opt
          name: volume name
        - name: mypd  # claim from pvc
            persistentVolumeClaim:
              claimName: myclaim
  volumes:
    - name: volume name
      hostPath:
        path: /data
        type: Directory